# Generated by Django 5.0.6 on 2024-07-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0002_tag_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(default='http://placehold.it/900x300'),
        ),
    ]
