# Generated by Django 5.0.6 on 2024-07-14 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0004_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='blog2.tag', verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(auto_created=True)),
                ('text', models.TextField(max_length=450)),
                ('avatar', models.URLField(default='https://as1.ftcdn.net/v2/jpg/03/46/83/96/1000_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws.jpg')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog2.post')),
            ],
            options={
                'db_table': 'custom_comments_new',
            },
        ),
    ]
