# Generated by Django 5.0.6 on 2024-07-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0005_alter_post_tags_comments'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='blog2_custom_comments_new',
        ),
    ]
