# Generated by Django 5.0.6 on 2024-07-15 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0011_country_city_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
