# Generated by Django 5.0.6 on 2024-07-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0014_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='user_avatar'),
        ),
    ]
